const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, '..', 'src', 'assets', 'Arif');
const publicDir = path.join(__dirname, '..', 'public', 'arif');
const outFile = path.join(__dirname, '..', 'src', 'data', 'arifProjects.ts');

if (!fs.existsSync(srcDir)) {
  console.error('Source folder not found:', srcDir);
  process.exit(1);
}

if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
}

const files = fs.readdirSync(srcDir).filter(f => /^IMG-|^[^.].*\.(jpg|jpeg|png|webp)$/i.test(f));

// categorization rules
const categories = {
  residential: [/villa|house|home|resid|project|project/i],
  commercial: [/commercial|mall|shop|retail|office/i],
  'high-rise': [/high|tower|skyscraper|multi|story|apartment/i],
  renovation: [/reno|remodel|renovation|upgrade|repair/i],
  turnkey: [/turnkey|end-to-end|complete|delivery/i],
  sustainable: [/green|eco|sustain|solar|energy/i],
  lakecity: [/lake/i]
};

const serviceKeys = Object.keys(categories);

const serviceProjects = {};
serviceKeys.forEach(k => serviceProjects[k] = []);
serviceProjects.residential = [];

files.forEach(file => {
  const srcPath = path.join(srcDir, file);
  const destPath = path.join(publicDir, file);
  try {
    fs.copyFileSync(srcPath, destPath);
  } catch (e) {
    console.error('copy failed', srcPath, e);
  }
  const lower = file.toLowerCase();
  let assigned = false;
  for (const key of serviceKeys) {
    const rules = categories[key];
    for (const r of rules) {
      if (r.test(lower)) {
        serviceProjects[key].push(`/arif/${file}`);
        assigned = true;
        break;
      }
    }
    if (assigned) break;
  }
  if (!assigned) {
    // default to residential
    serviceProjects.residential.push(`/arif/${file}`);
  }
});

// ensure arrays exist for services used in Services.tsx
const finalObj = {
  residential: serviceProjects.residential || [],
  commercial: serviceProjects.commercial || [],
  'high-rise': serviceProjects['high-rise'] || [],
  renovation: serviceProjects.renovation || [],
  turnkey: serviceProjects.turnkey || [],
  sustainable: serviceProjects.sustainable || [],
  lakecity: serviceProjects.lakecity || []
};

const tsContent = `// This file is auto-generated by scripts/generate_arif_projects.cjs\nexport const arifServiceProjects = ${JSON.stringify(finalObj, null, 2)} as Record<string, string[]>;\n`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, tsContent, 'utf8');
console.log('Generated', outFile);
console.log('Copied', files.length, 'files to public/arif');
